# Generated by Django 4.1.7 on 2023-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='in_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='out_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
