# Generated by Django 4.1.7 on 2023-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_alter_quantity_in_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='200gm', max_length=20),
        ),
    ]
