# Generated by Django 4.1.7 on 2023-03-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0009_customer_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
