# Generated by Django 4.1.7 on 2023-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0011_remove_order_customer_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='franchise_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='store_price',
            field=models.FloatField(default=0),
        ),
    ]
