# Generated by Django 4.1.7 on 2023-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0012_product_franchise_price_product_store_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default=210690, max_length=10),
        ),
    ]
