# Generated by Django 4.1.7 on 2023-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0013_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
