# Generated by Django 4.1.7 on 2023-08-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0016_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
