# Generated by Django 4.1.7 on 2023-03-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0011_remove_order_customer_remove_order_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(max_length=100)),
                ('fssai', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.FloatField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved')], max_length=30)),
                ('order_type', models.CharField(choices=[('super market', 'Super Market'), ('franchise', 'Franchise'), ('Studio', 'Studio')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='Billing.OrderItem', to='Stock.product'),
        ),
    ]
