# Generated by Django 4.1.7 on 2023-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='order_type',
            field=models.CharField(choices=[('super market', 'Super Market'), ('franchise', 'Franchise'), ('studio', 'Studio'), ('normal', 'Normal Customer')], default='studio', max_length=30),
        ),
    ]
