# Generated by Django 4.1.7 on 2023-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_remove_order_order_type_customer_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
