# Generated by Django 4.1.7 on 2023-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_of_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
