# Generated by Django 4.1.7 on 2023-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_type',
            field=models.CharField(choices=[('super market', 'Super Market'), ('franchise', 'Franchise'), ('normal', 'Normal Customer')], default='normal', max_length=30),
        ),
    ]
