# Generated by Django 4.1.7 on 2023-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0007_alter_customer_district_alter_customer_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
