# Generated by Django 4.1.7 on 2023-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0011_alter_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='franchise_id',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
