# Generated by Django 4.1.7 on 2023-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0012_customer_franchise_id_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
