# Generated by Django 4.1.7 on 2023-06-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0013_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.FloatField(default=0),
        ),
    ]
