# Generated by Django 4.1.7 on 2023-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0014_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
