# Generated by Django 4.1.7 on 2023-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0015_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
