# Generated by Django 4.1.7 on 2023-06-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0018_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='no_of_order',
        ),
    ]
