# Generated by Django 4.1.7 on 2023-07-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0019_remove_customer_no_of_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.order')),
                ('returned_items', models.ManyToManyField(through='Billing.ReturnItem', to='Billing.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='returnitem',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.salesreturn'),
        ),
    ]
