# Generated by Django 4.1.7 on 2023-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0020_returnitem_salesreturn_returnitem_sales_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='returned_items',
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ManyToManyField(to='Billing.orderitem'),
        ),
    ]
