# Generated by Django 4.1.7 on 2023-07-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0021_remove_returnitem_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='product',
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Billing.orderitem'),
        ),
    ]
