# Generated by Django 4.1.7 on 2023-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0022_remove_returnitem_product_returnitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='payment_status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='payment_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_total',
            field=models.FloatField(default=0),
        ),
    ]
