# Generated by Django 4.1.7 on 2023-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0024_alter_order_delivery_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='sales_return_total',
            field=models.FloatField(default=0.0),
        ),
    ]
