# Generated by Django 4.1.7 on 2024-04-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0025_salesreturn_sales_return_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
