# Generated by Django 4.1.7 on 2024-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0028_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_type',
            field=models.CharField(choices=[('super market', 'Distributor'), ('franchise', 'Franchise'), ('normal', 'Normal Customer'), ('exhibition', 'Exhibition')], default='normal', max_length=30),
        ),
    ]
