# Generated by Django 4.1.7 on 2024-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0029_alter_customer_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
