# Generated by Django 4.1.7 on 2025-02-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0032_alter_orderitem_batchno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=20),
        ),
    ]
