# Generated by Django 4.1.7 on 2025-03-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0033_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_number',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
    ]
