# Generated by Django 4.1.7 on 2023-04-09 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_alter_credit_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='credit',
            name='transaction_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
