# Generated by Django 4.1.7 on 2023-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_credit_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='how',
            field=models.CharField(choices=[('self', 'Self'), ('bank', 'Bank'), ('shop', 'Shop Cash')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='debit',
            name='person',
            field=models.CharField(default='', max_length=200),
        ),
    ]
