# Generated by Django 4.1.7 on 2023-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_debit_how_debit_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='transaction_number',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
