# Generated by Django 4.1.7 on 2023-06-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_credit_account_no_credit_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
