# Generated by Django 4.1.7 on 2023-06-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_debit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='debit',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('indirect', 'Indirect'), ('fixed', 'Fixed'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=20),
        ),
        migrations.CreateModel(
            name='DebitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_orders', to='Accounting.debit')),
            ],
        ),
        migrations.CreateModel(
            name='DebitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('debit_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_items', to='Accounting.debitorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.item')),
            ],
        ),
    ]
