# Generated by Django 4.1.7 on 2023-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_item_debit_type_debitorder_debititem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='account_no',
            new_name='cheque_no',
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
