# Generated by Django 4.1.7 on 2023-06-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_rename_account_no_credit_cheque_no_alter_credit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
