# Generated by Django 4.1.7 on 2023-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0011_alter_credit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
