# Generated by Django 4.1.7 on 2023-06-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0012_credit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('indirect', 'Indirect'), ('miscellaneous', 'Miscellaneous')], default='sales', max_length=20),
        ),
    ]
