# Generated by Django 4.1.7 on 2023-06-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0013_credit_credit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('miscellaneous', 'Miscellaneous')], max_length=15)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.debittype')),
            ],
        ),
        migrations.CreateModel(
            name='SubDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='debitorder',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='how',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='person',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='type',
        ),
        migrations.AlterField(
            model_name='debit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DebitItem',
        ),
        migrations.DeleteModel(
            name='DebitOrder',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='subdebit',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.debit'),
        ),
        migrations.AddField(
            model_name='debit',
            name='debit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.debittype'),
        ),
    ]
