# Generated by Django 4.1.7 on 2023-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0014_debittype_subdebit_remove_debitorder_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
