# Generated by Django 4.1.7 on 2023-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0015_debit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdebit',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subdebit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
