# Generated by Django 4.1.7 on 2023-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0016_subdebit_price_subdebit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdebit',
            name='quantity_type',
            field=models.CharField(choices=[('kgs', 'KGS'), ('pieces', 'Pieces')], default='kgs', max_length=20),
        ),
    ]
