# Generated by Django 4.1.7 on 2023-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0017_subdebit_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdebit',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
