# Generated by Django 4.1.7 on 2023-06-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0019_alter_subdebit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='date',
        ),
    ]
