# Generated by Django 4.1.7 on 2023-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0021_alter_debit_amount_alter_subdebit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdebit',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subdebit',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
    ]
