# Generated by Django 4.1.7 on 2023-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0023_subdebit_sub_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdebit',
            name='cgst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subdebit',
            name='sgst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
