# Generated by Django 4.1.7 on 2023-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0024_alter_subdebit_cgst_alter_subdebit_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdebit',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='subdebit',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subdebit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
