# Generated by Django 4.1.7 on 2023-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0026_alter_debittype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdebit',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'cash'), ('UPI', 'upi'), ('Cheque', 'Cheque'), ('Net Banking', 'net banking')], default='cash', max_length=100),
        ),
    ]
