# Generated by Django 4.1.7 on 2023-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0027_subdebit_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdebit',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('net banking', 'Net Banking')], default='cash', max_length=100),
        ),
    ]
