# Generated by Django 4.1.7 on 2023-07-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0028_alter_subdebit_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('balance_type', models.CharField(choices=[('Liability', 'Liability'), ('Asset', 'Asset')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='subdebit',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='subdebit',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='BalanceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('net banking', 'Net Banking')], max_length=20)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.balance')),
            ],
        ),
    ]
