# Generated by Django 4.1.7 on 2023-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0030_alter_balanceobject_amount_alter_balanceobject_cgst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='note',
        ),
        migrations.AddField(
            model_name='balance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
