# Generated by Django 4.1.7 on 2024-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0031_remove_balance_note_balance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='transaction_number',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
