# Generated by Django 4.1.7 on 2024-11-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0032_alter_credit_transaction_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='invoice_number',
            new_name='receipt_number',
        ),
    ]
